### ISSUE TITLE
Problème Création Séquence Cycle 4

### ISSUE THREAD

**Issue by b-breton** [cedrick-f/pySequence#8]
Bonjour,
j'ai un plantage lors de la création d'une Séquence Cycle 4 (que je n'ai pas rencontré pour les séquences STI2D).
Je travail avec la dernière version "pySequence_7.0-beta11", et la dernière version de Python "version 2.7.13".
Le Problème est le suivant (j'ai répété plusieurs fois l'opération, ça plante toujours au même moment):
Je crée une nouvelle séquence, je choisi ma classe, mes thématiques, mes prérequis, tout se passe bien. Quand je sélectionne les compétences j'ai 2 onglets "Sciences et technologie", dans le 1er je peux choisir une ou plusieurs compétences tout va bien, mais quand je sélectionne une compétence du 2nd onglet (Ex: CT2.4) le curseur passe en style "attente", le rafraîchissement de la fenêtre est figé et j'ai ce message d'erreur dans la console Python:
Traceback (most recent call last):
  File "wx_pysequence.py", line 3423, in OnResize
  File "wx_pysequence.py", line 3599, in Redessiner
  File "wx_pysequence.py", line 3585, in redess
  File "wx_pysequence.py", line 3616, in Draw
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\draw_cairo_seq.py", line 677, in Draw
KeyError: u'CT'

Je ne vois pas comment régler le problème. Quelqu'un aurait-il une idée?
Merci

**Comment by cedrick-f** [comment]
Bonjour

La fonctionnalité Progression est encore très largement en phase de 
développement.

Cependant, elle s'améliore à chaque version. Je conseille donc 
d'utiliser aujourd'hui la 7.1-beta5 
<https://github.com/cedrick-f/pySequence/releases/tag/v7.1-beta.5> ... 
merci de bien faire remonter tous les bugs rencontrés et autres 
observations.


CF
