### ISSUE TITLE
Importation séquence dans progression 8.4-beta16

### ISSUE THREAD

**Issue by michelwend** [cedrick-f/pySequence#82]
Bonjour,
Lorsque je cherche à importer une séquence supplémentaire dan une progression existante pyséquence se fige comme celà:
![image](https://user-images.githubusercontent.com/11646494/82602077-cdf29d00-9bb0-11ea-8218-9bd028e0091b.png)
Voici le fichier de suivi:

`  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\pysequence.py", line 6953, in AjouterSequence
wx._core.wxAssertionError: C++ assertion ""Assert failure"" failed at ..\..\src\msw\toplevel.cpp(411) in wxTopLevelWindowMSW::CreateDialog(): Failed to create dialog. Incorrect DLGTEMPLATE?
Traceback (most recent call last):
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\pysequence.py", line 6941, in AjouterSequence
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\pysequence.py", line 7351, in GetFichiersSequencesDossier
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\pysequence.py", line 7132, in OuvrirFichierSeq
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\pysequence.py", line 2212, in __init__
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\pysequence.py", line 1718, in __init__
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\pysequence.py", line 622, in __init__
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\objects_wx.py", line 19187, in __init__
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\objects_wx.py", line 19720, in SetPage
wx._core.wxAssertionError: C++ assertion ""((HWND)GetHWND())"" failed at ..\..\src\msw\window.cpp(1260) in wxWindow::GetLayoutDirection(): invalid window`
Bien cordialement

**Comment by cedrick-f** [comment]
Bonjour
D'après la capture d'écran, il semblerait que le problème provienne d'une séquence en particulier. Est-ce qu'elle s'ouvre correctement, en dehors d'une progression ?
CF

**Comment by michelwend** [comment]
Bonjour,
J'ai ouvert et affiché la progression ainsi que toutes les séquences cote à cote sans problème.

**Comment by cedrick-f** [comment]
Je n'arrive pas à reproduire l'erreur ...

**Comment by michelwend** [comment]
Bonsoir,
Lorsque vous commencez la progression les séquences se mettent l'une à la suite de l'autre?
Si ce n'est pas le cas vous arrivez à déplacer une séquence dans la progression?
Merci pour votre retour

**Comment by michelwend** [comment]
C'est le même type de souci que:
https://github.com/cedrick-f/pySequence/issues/83

**Comment by cedrick-f** [comment]
Toujours pas moyen de reproduire l'erreur. J'ai quand même rajouté des sécurités dans la version beta18.
Quant au déplacement des séquences, je n'ai pas rencontré de problème. Mais ça ne peut pas se faire par glisser/déposer, c'est normal (c'est trop compliqué à faire car une séquence peut être positionnée sur plusieurs périodes de l'année)
Voici ce que ça donne si on utilise les "créneaux" pour éviter les chevauchements
![image](https://user-images.githubusercontent.com/11462584/82756353-09bc7b00-9dda-11ea-9d07-0ad80d41cec5.png)
