### ISSUE TITLE
ouverture séquences dans progression 8.4-17

### ISSUE THREAD

**Issue by michelwend** [cedrick-f/pySequence#89]
Bonjour,
J'ai fais un premier essai d'ajout de mes séquences dans une progression. L'ordre n'est toujours pas respecté.
Pour mon deuxième essai je mets toutes mes séquences sur l'ensemble de la première. Cela a fonctionné pour les deux premières séquences. Lors de l'incorporation de la troisième j'ai le message d'erreur suivant:
`Différence
   labels
  xml: {'SEQINT': ['Intitulé de la Séquence', 'Intitulé de la Séquence pédagogique', <widgets.Grammaire object at 0x1A60F350>], 'ELEVES': ['Élève(s)$m', 'Élèves', <widgets.Grammaire object at 0x1A60F190>], 'OBJEC': ['Objectif(s) de formation$m', 'Objectifs de formation', <widgets.Grammaire object at 0x1A60F4F0>], 'PRJVAL': ['Fiche(s) de validation de projet$f', 'Fiche de validation de projet', <widgets.Grammaire object at 0x1A60F410>], 'EXIG': ['Fonction(s) de service$f', 'Fonctions de service', <widgets.Grammaire object at 0x1A60F470>]}
  xls: {'SEQINT': ['Intitulé de la Séquence', 'Intitulé de la Séquence pédagogique', <widgets.Grammaire object at 0x05FD9850>], 'ELEVES': ['Élève(s)$m', 'Élèves', <widgets.Grammaire object at 0x05FD37D0>], 'OBJEC': ['Objectif(s) de formation$m', 'Objectifs de formation', <widgets.Grammaire object at 0x05FD37B0>]}
Traceback (most recent call last):
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\pysequence.py", line 7013, in AjouterSequence
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\pysequence.py", line 7428, in GetFichiersSequencesDossier
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\pysequence.py", line 7207, in OuvrirFichierSeq
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\pysequence.py", line 1066, in __init__
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\pysequence.py", line 623, in __init__
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\objects_wx.py", line 19199, in __init__
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\objects_wx.py", line 19732, in SetPage
wx._core.wxAssertionError: C++ assertion ""((HWND)GetHWND())"" failed at ..\..\src\msw\window.cpp(1260) in wxWindow::GetLayoutDirection(): invalid window
`
De manière plus générale:
*Le temps d'incorporation est très long>1min30
*D'après nos échanges j'ai bien compris que le choix des propriétés des dates avec le bargraph horizontal est primordial. Quel est la stratégie à mettre œuvre pour que cela fonctionne à chaque fois. Car des fois l'ordre des séquences peu évoluer. Faut-il permettre l'année complète dans les propriétés des séquences puis ajuster une fois importer dans la progression? Quelles est la stratégie?
En vous remerciant encore pour tout le travail déjà accompli.
mw

**Comment by cedrick-f** [comment]
Les 3 séquences sont positionnées sur les 5 périodes de 1ère. 
![image](https://user-images.githubusercontent.com/11462584/82758289-eac3e600-9de5-11ea-9fc0-3c33cbe0fa5a.png)

Elles se chevauchent donc sur la fiche : 
![image](https://user-images.githubusercontent.com/11462584/82758279-d384f880-9de5-11ea-9649-56840f10fcfd.png)


Pour éviter cela, il faut :
 * soit "jouer" avec les créneaux :
![image](https://user-images.githubusercontent.com/11462584/82758328-29f23700-9de6-11ea-8810-ec9d145e3cb0.png)

 * soit changer les positions :
![image](https://user-images.githubusercontent.com/11462584/82758381-8a817400-9de6-11ea-855b-1a159209b5dc.png)

> Le temps d'incorporation est très long>1min30
Ça ira plus vite dans la version 8.4-beta.18, promis !

> Faut-il permettre l'année complète dans les propriétés des séquences puis ajuster une fois importer dans la progression? Quelles est la stratégie?
Les Séquences ouvertes dans la Progression (même celles qui n'ont pas d'onglet propre), sont modifiées via la Progression : un changement de position d'une Séquence dans la Progression se traduira par une modification du fichier Séquence.

**Comment by michelwend** [comment]
Bonsoir,
On est bien d'accord que "jouer" sur les créneaux s'effectue dans les propriétés des fichiers séquence? Par contre changer les positions ne peut s'effectuer que dans un fichier "progression" à condition toutefois que les créneaux définis dans les propriétés des séquences soient compatibles?
Merci pour les précisions que vous voudrez bien apporter à ce sujet.
Bien cordialement
mw

**Comment by cedrick-f** [comment]
Les **positions** des séquences (avec le _RangeSlider_) peut se faire depuis le fichier _Séquence_ ou bien depuis le fichier _Progression_. Les **positions** permettent d'ordonner chronologiquement les _séquences_ ou _projets_ qui doivent l'être (pour des raisons de prérequis essentiellement).

Les **créneaux** sont modifiables depuis le fichier _Progression_ seulement. C'est une notion permettant de traiter plusieurs _séquences_ ou _projet_ "simultanément". Selon les emploi du temps hebdomadaire, une _séquence_ ou un _projet_ peut occuper 4h/semaine, 2h/semaine, 2h/quinzaine, ... d'où la "simultanéité" au niveau d'une **période** (en gros, entre deux vacances, mais ça dépend des référentiels).

La **Compatibilité** est évaluée depuis le fichier _Progression_ : la branche "Séquences et Projets" passe en rouge s'il y a un problème, et une info-bulle précise. Mais globalement, on visualise les problèmes sur la fiche directement :
- chevauchement
- zone "vides"
- périodes beaucoup trop remplies que d'autres

En espérant avoir été clair...
CF
