### ISSUE TITLE
ouverture séquences dans progression 8.4-18

### ISSUE THREAD

**Issue by michelwend** [cedrick-f/pySequence#90]
Bonsoir,
Le temps reste du même ordre que précédemment. La commande retour "flèche jaune arrière, undo" ne fonctionne pas. J'ai réussi à importer 5 séquences mai s la 6e il n'en a pas voulu peut-être un problème de créneaux, à voir demain. Effectivement les cases à cocher pour l'importation apporte un réel plus, mais ce serai peut-être bien que l'on puisse sélectionner des fichiers projets en même temps? Merci

`Différence
   labels
  xml: {'SEQINT': ['Intitulé de la Séquence', 'Intitulé de la Séquence pédagogique', <widgets.Grammaire object at 0x06CB3BF0>], 'ELEVES': ['Élève(s)$m', 'Élèves', <widgets.Grammaire object at 0x06CB3630>], 'OBJEC': ['Objectif(s) de formation$m', 'Objectifs de formation', <widgets.Grammaire object at 0x06CB3150>], 'PRJVAL': ['Fiche(s) de validation de projet$f', 'Fiche de validation de projet', <widgets.Grammaire object at 0x06CB3050>], 'EXIG': ['Fonction(s) de service$f', 'Fonctions de service', <widgets.Grammaire object at 0x06CB3CB0>]}
  xls: {'SEQINT': ['Intitulé de la Séquence', 'Intitulé de la Séquence pédagogique', <widgets.Grammaire object at 0x0689BE90>], 'ELEVES': ['Élève(s)$m', 'Élèves', <widgets.Grammaire object at 0x06897DD0>], 'OBJEC': ['Objectif(s) de formation$m', 'Objectifs de formation', <widgets.Grammaire object at 0x06897D90>]}
Traceback (most recent call last):
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\objects_wx.py", line 1645, in commandeUndo
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\objects_wx.py", line 2345, in commandeUndo
AttributeError: 'FenetreProgression' object has no attribute 'restaurer'`

**Comment by michelwend** [comment]
Lorsque je joue sur les créneaux des séquences dans le fichier de la progression j'ai ce type d'erreur qui apparait:
`Différence
   labels
  xml: {'SEQINT': ['Intitulé de la Séquence', 'Intitulé de la Séquence pédagogique', <widgets.Grammaire object at 0x062E4690>], 'ELEVES': ['Élève(s)$m', 'Élèves', <widgets.Grammaire object at 0x062E4DF0>], 'OBJEC': ['Objectif(s) de formation$m', 'Objectifs de formation', <widgets.Grammaire object at 0x062E4FD0>], 'PRJVAL': ['Fiche(s) de validation de projet$f', 'Fiche de validation de projet', <widgets.Grammaire object at 0x062E4470>], 'EXIG': ['Fonction(s) de service$f', 'Fonctions de service', <widgets.Grammaire object at 0x062E4B50>]}
  xls: {'SEQINT': ['Intitulé de la Séquence', 'Intitulé de la Séquence pédagogique', <widgets.Grammaire object at 0x0669BE90>], 'ELEVES': ['Élève(s)$m', 'Élèves', <widgets.Grammaire object at 0x06697DB0>], 'OBJEC': ['Objectif(s) de formation$m', 'Objectifs de formation', <widgets.Grammaire object at 0x06697D90>]}
c: Lc: Lc: Lcairocffi.CairoError
c: Lms: L`

**Comment by michelwend** [comment]
**Graphisme**
J'ai pour l'instant choisi de mettre mes 6 séquences sur toute l'année mais visuellement dans la partie graphique l'affichage ne correspond pas:
![image](https://user-images.githubusercontent.com/11646494/82762109-7302b500-9dff-11ea-92a7-ff2436db5ec7.png)

Pour les projets le le bargraph de la terminale est différent de la première
![image](https://user-images.githubusercontent.com/11646494/82762146-ae04e880-9dff-11ea-84f3-c2ce4cb8fac7.png)
De plus comment afficher entièrement la fen^tre graphique pour les projets, les séquences, la progression? Je n'arrive à voir la partie graphique en entier?
![image](https://user-images.githubusercontent.com/11646494/82762196-f7edce80-9dff-11ea-8c19-dceced94990d.png)

**Comment by michelwend** [comment]
Pour l'insertion d'un projet j'obtiens cette erreur
`Traceback (most recent call last):
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\objects_wx.py", line 14133, in OnSelChanged
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\pysequence.py", line 8270, in GetPanelPropriete
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\objects_wx.py", line 9696, in __init__
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\objects_wx.py", line 9752, in construire
wx._core.wxAssertionError: C++ assertion "!(flags & (wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL))" failed at ..\..\src\common\sizer.cpp(2089) in wxBoxSizer::DoInsert(): Horizontal alignment flags are ignored with wxEXPAND
c: Lc: Lc: Lc: Lms: LTraceback (most recent call last):
  File "C:\Users\Cedrick\AppData\Local\Programs\Python\Python36-32\lib\site-packages\wx\core.py", line 2311, in Notify
  File "C:\Users\Cedrick\AppData\Local\Programs\Python\Python36-32\lib\site-packages\wx\core.py", line 3508, in Notify
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\pysequence.py", line 2080, in SetAndShowTip
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\pysequence.py", line 8214, in SetTip
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\pysequence.py", line 1871, in GetApercu
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\draw_cairo2.py", line 827, in getBitmap
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\draw_cairo2.py", line 819, in getImageSurface
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\draw_cairo_seq2.py", line 585, in draw
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\draw_cairo2.py", line 992, in draw
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\draw_cairo2.py", line 1319, in _draw
  File "C:\Users\Cedrick\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cairocffi\context.py", line 2003, in text_extents
  File "C:\Users\Cedrick\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cairocffi\context.py", line 107, in _check_status
  File "C:\Users\Cedrick\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cairocffi\__init__.py", line 88, in _check_status
MemoryError: ("cairo returned CAIRO_STATUS_NO_MEMORY: b'out of memory'", 1)`

**Comment by michelwend** [comment]
L'intégration des projets dans la progression pose problème, même si j'ai fais évolué le créneau sur l'ensemble de l'année de première.
`Traceback (most recent call last):
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\objects_wx.py", line 14133, in OnSelChanged
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\pysequence.py", line 8270, in GetPanelPropriete
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\objects_wx.py", line 9696, in __init__
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\objects_wx.py", line 9752, in construire
wx._core.wxAssertionError: C++ assertion "!(flags & (wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL))" failed at ..\..\src\common\sizer.cpp(2089) in wxBoxSizer::DoInsert(): Horizontal alignment flags are ignored with w`

**Comment by cedrick-f** [comment]
Bonjour

> La commande retour "flèche jaune arrière, undo" ne fonctionne pas
Merci, j'ai résolu le problème.

> J'ai réussi à importer 5 séquences mai s la 6e il n'en a pas voulu peut-être un problème de créneaux
Je n'arrive toujours pas à reproduire ce bug .......

> J'ai pour l'instant choisi de mettre mes 6 séquences sur toute l'année
Je ne comprends pas comment on peut mener simultanément 6 séquences pendant toute l'année avec 4h de cours par semaine.

> Pour les projets le le bargraph de la terminale est différent de la première
Rien d'anormal. En terminale le projet obligatoire occupe une grande partie de l'année et il n'est pratiquement pas possible d'en mener d'autres.
En première, le projet obligatoire peut se dérouler de manière plus "étalée".


> comment afficher entièrement la fen^tre graphique pour les projets, les séquences, la progression? Je n'arrive à voir la partie graphique en entier?
C'est un choix qui a été fait depuis le début de pySéquence : proposer des fiches au format A4, pour impression. Sur certains écrans, il peut être impossible de les afficher entièrement.

Erreur : `Horizontal alignment flags are ignored`
Merci. C'est résolu.

Quant à l'erreur en `'out of memory'` je n'ai malheureusement pas de solution ...

**Comment by michelwend** [comment]
Bonjour,
`J'ai pour l'instant choisi de mettre mes 6 séquences sur toute l'année.
Je ne comprends pas comment on peut mener simultanément 6 séquences pendant toute l'année avec 4h de cours par semaine.`
Il s'agit en fait de mettre les 6 séquences l'une à la suite de l'autre et non simultanément. J'ai choisi dans un premier temps d'incorporer ainsi les séquences dans la progression pour facilement les déplacer. Je vais maintenant effectivement les limiter dans le temps pour les faire successivement et non concomitamment.
`Pour les projets le le bargraph de la terminale est différent de la première
Rien d'anormal. En terminale le projet obligatoire occupe une grande partie de l'année et il n'est pratiquement pas possible d'en mener d'autres.
En première, le projet obligatoire peut se dérouler de manière plus "étalée".`
D'accord.
Pour moi cette issue terminée. Si cela vous convient vous pouvez la clore. J'en créerai une autre pour vous suggérer éventuellement un aménagement de menus si cela vous agrée.

Merci en tout cas pour vos réponses et votre travail.
